### ISSUE TITLE
Prepare symlink task for Ansible 2.10

### ISSUE THREAD

**Issue by tofi86** [arillso/ansible.logrotate#14]
Hi, first of all thank you for maintaining this role!

Running a fairly simple configuration 

```yml
logrotate_applications:
  - name: printcss-services
    definitions:
      - logs:
          - /var/log/printcss-api/out.log
          - /var/log/printcss-api/error.log
          - /var/log/printcss-daemon/out.log
          - /var/log/printcss-daemon/error.log
          - /var/log/printcss-frontend/out.log
          - /var/log/printcss-frontend/error.log
        options:
          - rotate 100
          - size 25M
          - weekly
          - missingok
          - notifempty
```

with Ansible 2.8.1 on Mac OS 10.14 with Python 3 I get the following warning for a deployment to Ubuntu 18.04 LTS:

```
TASK [arillso.logrotate : Symlink for hourly rotation]
********************************************************************
 [WARNING]: The src option requires state to be 'link' or 'hard'.
 This will become an error in Ansible 2.10
```

My playbook works, I just wanted to place this in the issue tracker as a note for you and others... :-)

Thanks!
