### ISSUE TITLE
Addition to README

### ISSUE THREAD

**Issue by mfredholm** [arillso/ansible.logrotate#3]
Hi,
I had some struggle to figure out correct syntax so maybe it could be helpful to add some working example on how to use 'logrotate_applications' in the README file?
Like this:

```
logrotate_applications:
  - name: zabbix-agent
    definitions:
      - logs:
          - '/var/log/zabbix/zabbix_agentd.log'
        options:
          - weekly
          - rotate 13
          - compress
          - delaycompress
          - missingok
          - notifempty
          - create 0640 zabbix zabbix
```

Regards
Mats
